### ISSUE TITLE
What is cfg.yaml proper format?

### ISSUE THREAD

**Issue by JRWallace** [compbiocore/refchef#30]
- Here's an example of a `cfg.yaml` file:

```
config-yaml:
  path-settings:
    reference-directory: /Volumes/jwalla12/references #directory where references will be downloaded and processed.
    github-directory: /Volumes/jwalla12/local_references #local git repository where `master.yaml` is located.
    remote-repository: jrwallace/local_references #remote user and repository for version control of `master.yaml`
  log-settings
    log: 'yes'
```

However, running refchef-cook using this yaml yields an error:
```
(base) CIS2703FHTDH:local_references jwalla12$ refchef-cook -e -g commit -c '/Volumes/jwalla12/local_references/cfg.yaml' 
/anaconda3/lib/python3.7/site-packages/refchef/utils.py:12: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  dict_ = yaml.load(yml)
Malformatted config file. See the documentation for details at
                https://compbiocore.github.io/refchef
```
