### ISSUE TITLE
adding a new.yaml to master.yaml is not appending the master.yaml with the new keys

### ISSUE THREAD

**Issue by JRWallace** [compbiocore/refchef#40]
Adding new files to the same key (an index, some annotations) works fine, but adding a new key to master.yaml isn't working properly -- the files will download but the commands aren't actually added to master.yaml

I tried:
```
refchef-cook -e -o /Users/jwalla12/references -gl /Users/jwalla12/remote_references -gr jrwallace/remote_references --new /Users/jwalla12/Repositories/remote_references/new.yaml --git commit -l 
```
as well as
```
refchef-cook -e -a -o /Users/jwalla12/references -gl /Users/jwalla12/remote_references -gr jrwallace/remote_references --new /Users/jwalla12/Repositories/remote_references/new.yaml --git commit -l 
```
and
```
refchef-cook -a -o /Users/jwalla12/references -gl /Users/jwalla12/remote_references -gr jrwallace/remote_references --new /Users/jwalla12/Repositories/remote_references/new.yaml --git commit -l 
```

master.yaml:
```
S_cerevisiae:
  metadata:
    name: S_cerevisiae
    common_name: yeast
    ncbi_taxon_id: 4932
    organism: Saccharomyces cerevisiae
    organization: ensembl
    custom: false
    description: corresponds to ganbank id GCA_000146045.2
    downloader: joselynn wallace
    ensembl_release_number: 87
    accession:
      genbank: null
      refseq: null
  levels:
    references:
    - component: primary
      complete:
        status: true
        time: '2019-08-27 15:16:45.447179'
      commands:
      - wget ftp://ftp.ensembl.org/pub/release-87/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa.gz
      - wget ftp://ftp.ensembl.org/pub/release-87/fasta/saccharomyces_cerevisiae/dna/CHECKSUMS
      - md5 *.gz > postdownload-checksums.md5
      - gunzip *.gz
      - md5 *.* > final_checksums.md5
      location: /Users/jwalla12/references/S_cerevisiae/primary
      files:
      - metadata.txt
      - postdownload-checksums.md5
      - CHECKSUMS
      - final_checksums.md5
      - Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa
      uuid: dff337a6-9a1d-3313-8ced-dc6f3bfc9689
    annotations:
    - component: gtf
      complete:
        status: true
        time: '2019-08-27 15:16:52.548696'
      commands:
      - wget ftp://ftp.ensembl.org/pub/release-87/gtf/saccharomyces_cerevisiae/Saccharomyces_cerevisiae.R64-1-1.87.gtf.gz
      - wget ftp://ftp.ensembl.org/pub/release-87/gtf/saccharomyces_cerevisiae/CHECKSUMS
      - md5 *.gz > postdownload-checksums.md5
      - gunzip *.gz
      - md5 *.* > final_checksums.md5
      location: /Users/jwalla12/references/S_cerevisiae/gtf
      files:
      - metadata.txt
      - postdownload-checksums.md5
      - Saccharomyces_cerevisiae.R64-1-1.87.gtf
      - CHECKSUMS
      - final_checksums.md5
      uuid: 5f7ae94c-2e51-3cc6-bcbf-6e251c75ef2f
```
new.yaml:
```
spur31:
  metadata:
    name: spur31
    common_name: purple sea urchin
    custom: no
    description: corresponds to GCA_000002235.2
    downloader: joselynn
    ncbi_taxon_id: 7668
    ensembl_release_number: 43
    accession:
      genbank:
      refseq:
    organism: Strongylocentrotus purpuratus
    organization: ensembl metazoa
  levels:
    references:
    - component: primary
      complete:
        status: false
      commands:
      - wget ftp://ftp.ensemblgenomes.org/pub/release-43/metazoa/fasta/strongylocentrotus_purpuratus/dna/CHECKSUMS
      - wget ftp://ftp.ensemblgenomes.org/pub/release-43/metazoa/fasta/strongylocentrotus_purpuratus/dna/Strongylocentrotus_purpuratus.Spur_3.1.dna.toplevel.fa.gz
      - md5 * > final_checksums.md5
```
